### PR TITLE
allow to specify constant folding and dead code elimination optimizations

### PR DESCRIPTION
**Pull request by magalhas**
As asked in #105, this the implementation of that same feature.

### CODE REVIEW

**Comment by michaelficarra** [comment]
No, I think we should have a more general facility for enabling and disabling passes.

**Comment by magalhas** [comment]
Something like `passes: {[passName]: true/false}`? All of them implicitly enabled by default.

**Comment by michaelficarra** [comment]
Yeah, probably. We may be able to come up with something better.

**Comment by magalhas** [comment]
I've just changed things a little bit, the way it works is simple, if you supply a `passes` object to the `esmangle.optimize` options it will only pick the passes/transformations that are set as true (pass names should be camel cased in this scenario). If there's no passes object defined then everything works as always.

Example (to only apply constant folding):
```
tree = esmangle.optimize(tree, null, {
    passes: {
      treeBasedConstantFolding: true
    }
});
```

Other example applying most of the dead code elimination features:
```
tree = esmangle.optimize(tree, null, {
    passes: {
      deadCodeElimination: true,
      eliminateDuplicateFunctionDeclarations: true,
      removeEmptyStatement: true,
      removeUnusedLabel: true,
      removeUnreachableBranch: true,
      removeSideEffectFreeExpressions: true,
      removeWastedBlocks: true
    }
});
```

Missing: unit tests. Let me know if this implementation looks good enough.

**Comment by michaelficarra** [comment]
Yes, this looks much better to me.

**Comment by magalhas** [comment]
Not sure what's the best approach to implement an unit test for this. Can you please take a look at it? The feature is working fine on our project anyway. It would be awesome to see a new release of esmangle soon so that we can "get rid" of the fork (and our git+https dependency which slows a lot the build).

**Comment by magalhas** [comment]
@michaelficarra

**Comment by michaelficarra** [comment]
Fine, we'll ignore tests for now. Thanks for the contribution.

**Pull request merged**
