### PR TITLE
update estraverse version to newest for supporting es6 feature.

### PR DESCRIPTION
**Pull request by yuzhigang33**

### CODE REVIEW

**Comment by yuzhigang33** [comment]
@michaelficarra

**Comment by Constellation** [comment]
It seems that `esutils` API change causes the failures of the tests.
Could you update the use of APIs?

**Comment by yuzhigang33** [comment]
@Constellation Oh,sorry for that. Now i fix the test case;

**Comment by Constellation** [comment]
Thanks, :D

**Pull request merged**
